// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6PbaWcNOy7zRqXXd5Y96fqX0XzhoUqm8',
    appId: '1:451241191068:web:dd56ff17a3f73e5ecd2f59',
    messagingSenderId: '451241191068',
    projectId: 'invengo-project',
    authDomain: 'invengo-project.firebaseapp.com',
    storageBucket: 'invengo-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdUu0mgeEwJq5dm5eeWVVfBc5nFuy8XH4',
    appId: '1:451241191068:android:fc7bf1fab03667e9cd2f59',
    messagingSenderId: '451241191068',
    projectId: 'invengo-project',
    storageBucket: 'invengo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-woV8tQkJDEHlckpSBhXmFBXsLe2Gnps',
    appId: '1:451241191068:ios:a2ab18bf699bd794cd2f59',
    messagingSenderId: '451241191068',
    projectId: 'invengo-project',
    storageBucket: 'invengo-project.firebasestorage.app',
    iosBundleId: 'com.ppkd.invengo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-woV8tQkJDEHlckpSBhXmFBXsLe2Gnps',
    appId: '1:451241191068:ios:a2ab18bf699bd794cd2f59',
    messagingSenderId: '451241191068',
    projectId: 'invengo-project',
    storageBucket: 'invengo-project.firebasestorage.app',
    iosBundleId: 'com.ppkd.invengo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6PbaWcNOy7zRqXXd5Y96fqX0XzhoUqm8',
    appId: '1:451241191068:web:50710bd98550f7c0cd2f59',
    messagingSenderId: '451241191068',
    projectId: 'invengo-project',
    authDomain: 'invengo-project.firebaseapp.com',
    storageBucket: 'invengo-project.firebasestorage.app',
  );
}
